apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment-multi
  namespace: nginx-multi
  labels:
    app.kubernetes.io/name: nginx-multi
spec:
  replicas: 4
  selector:
    matchLabels:
      app: nginx-multi
  template:
    metadata:
      labels:
        app: nginx-multi
    spec:
      containers:
      - name: nginx
        image: public.ecr.aws/nginx/nginx:latest
        ports:
        - containerPort: 80